[general]
import = [
    "themes/moonfly.toml"
]

[window]
#opacity = 0.80
dynamic_title = false
#decorations = "none"

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.normal]
family = "terminus"
style = "Bold"

[font.bold]
family = "terminus"
style = "Bold"
